on: push
name: CI on code push
jobs:
  phpunit-with-node:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    strategy:
      matrix:
        node-version: [18.x]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
 
    - name: Install Laravel composer dependencies
      run: |
        cd amp-app && composer install --no-scripts
 
    - name: Prepare Laravel Environments
      run: |
        cd amp-app && cp .env.ci .env
        php artisan key:generate

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm dependencies
      run: cd amp-app && npm ci

    - name: NPM Build
      run: cd amp-app && npm run build

    - name: Run Pint for code style
      run: cd amp-app && ./vendor/bin/pint --test

    - name: Run Testsuite
      run: cd amp-app && php artisan test